import fs from "node:fs";
import path from "node:path";
import { walkPages, type PageEntry } from "./walk-pages";

export interface GuideEntry {
  slug: string;
  title: string;
  description: string;
  datePublished: string;
  href: string;
  sections: { id: string; title: string }[];
  hasFaq: boolean;
}

let cachedDir: string | null = null;
let cachedGuides: GuideEntry[] | null = null;

/**
 * Legacy helper that discovers guides under a specific content directory.
 * Internally delegates to walkPages() then filters to the relevant path prefix.
 *
 * For new integrations, prefer walkPages() directly.
 */
export function discoverGuides(contentDir?: string): GuideEntry[] {
  const dir = contentDir ?? path.join(process.cwd(), "src/app/(content)/t");

  if (cachedDir === dir && cachedGuides) return cachedGuides;

  // Try to load the build-time manifest first (generated by withSeoContent).
  // This is required on Vercel where fs.readdirSync can't walk source dirs.
  // Check both project root and .next/ for backwards compat.
  const candidates = [
    path.join(process.cwd(), "seo-guides-manifest.json"),
    path.join(process.cwd(), ".next", "seo-guides-manifest.json"),
  ];
  let manifestPages: PageEntry[] | null = null;
  for (const manifestPath of candidates) {
    try {
      const raw = fs.readFileSync(manifestPath, "utf-8");
      const manifest = JSON.parse(raw);
      if (Array.isArray(manifest.pages)) {
        manifestPages = manifest.pages;
        break;
      }
    } catch {
      // Try next candidate
    }
  }

  let guides: GuideEntry[];

  if (manifestPages && manifestPages.length > 0) {
    guides = manifestPages.map(pageToGuide);
  } else {
    // Fallback: walk the filesystem (works locally, may fail on Vercel)
    const relDir = path.relative(process.cwd(), dir);
    const relParts = relDir.split(path.sep);
    const appIdx = relParts.indexOf("app");
    const appDir =
      appIdx >= 0
        ? path.join(process.cwd(), ...relParts.slice(0, appIdx + 1))
        : path.join(process.cwd(), "src/app");
    const allPages = walkPages({ appDir });

    const relative = path.relative(appDir, dir);
    const segments = relative
      ? relative
          .split(path.sep)
          .filter((s) => !(s.startsWith("(") && s.endsWith(")")))
      : [];
    const hrefPrefix = "/" + segments.join("/");

    const filterPrefix = hrefPrefix === "/" ? "/" : hrefPrefix + "/";
    guides = allPages
      .filter((p) => p.href.startsWith(filterPrefix) && p.href !== hrefPrefix)
      .map(pageToGuide);
  }

  guides.sort(
    (a, b) =>
      (b.datePublished || "").localeCompare(a.datePublished || "") ||
      a.title.localeCompare(b.title),
  );

  cachedDir = dir;
  cachedGuides = guides;
  return guides;
}

function pageToGuide(p: PageEntry): GuideEntry {
  const parts = p.href.split("/");
  const slug = parts[parts.length - 1] || "";
  return {
    slug,
    title: p.title,
    description: p.description,
    datePublished: p.datePublished ?? "",
    href: p.href,
    sections: p.sections,
    hasFaq: p.sections.some(
      (s) => s.id === "frequently-asked-questions",
    ),
  };
}
